### ISSUE TITLE
启动chromium失败

### ISSUE THREAD

**Issue by fatinghenji** [koishijs/koishi-android#10]
```java
2023-05-04 17:18:43 [I] puppeteer chrome executable found at /bin/chromium
2023-05-04 17:18:45 [W] app Error: Failed to launch the browser process!
                        [0504/171845.195712:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/07sk2rd752f0y46ym3mmjxvsd9175x5f-chromium-102.0.5005.115-sandbox/bin/__chromium-suid-sandbox is owned by root and has mode 4755.
                        
                        
                        TROUBLESHOOTING: https://pptr.dev/troubleshooting
                        
                            at onClose (/home/koishi-app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:300:20)
                            at ChildProcess.<anonymous> (/home/koishi-app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:291:24)
                            at ChildProcess.emit (node:events:539:35)
                            at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by Anillc** [comment]
尝试在控制台 puppeteer 插件的配置项中配置 `--no-sandbox` 参数
